service:
  enabled: true
  name: helloworld-go
  type: ClusterIP
  ports:
    app:
      port: 9000
      targetPort: http
      protocol: TCP


replicas: 1
image:
  repository: "myapp_image"
  tag: "latest"
  pullPolicy: "IfNotPresent"
